Style the <options> for visibility's sake
This PR represents an attempt to service issue #33 .

I tried pulling the repo and running `npm run build`, but was unable to due to some binary structure I don't see documentation of.

```
$ npm run build

> codemirror-website@0.0.1 build
> node src/index.js

node:internal/modules/cjs/loader:949
  throw err;
  ^

Error: Cannot find module '../../bin/packages'
Require stack:
- C:\Users\john\projects\external\website\src\buildref.js
- C:\Users\john\projects\external\website\src\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\john\projects\external\website\src\buildref.js:7:30)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12)
    at Module.require (node:internal/modules/cjs/loader:1012:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\john\\projects\\external\\website\\src\\buildref.js',
    'C:\\Users\\john\\projects\\external\\website\\src\\index.js'
  ]
}
```